- name: be sure wing repositories is installed
  get_url: url=http://wing-repo.net/wing/6/EL6.wing.repo dest=/etc/yum.repos.d/EL6.wing.repo mode=0440

- name: enable off repositories
  replace: dest=/etc/yum.repos.d/EL6.wing.repo regexp="enabled *= *1" replace="enabled=0"

- name: be sure git is installed
  yum: name=git enablerepo=wing state=present
